### ISSUE TITLE
Cannot build on Xenial, webRTC API seems to have changed.

### ISSUE THREAD

**Issue by hmahadik** [mpromonet/webrtc-streamer#107] opened 2018-03-23 16:59 UTC
```
src/PeerConnectionManager.cpp: In member function ‘bool PeerConnectionManager::streamStillUsed(const string&)’:
src/PeerConnectionManager.cpp:521:29: error: ‘class webrtc::MediaStreamInterface’ has no member named ‘label’
    if (localstreams->at(i)->label() == streamLabel)
                             ^
src/PeerConnectionManager.cpp: In member function ‘const Json::Value PeerConnectionManager::hangUp(const string&)’:
src/PeerConnectionManager.cpp:551:51: error: ‘class webrtc::MediaStreamInterface’ has no member named ‘label’
    std::string streamLabel = localstreams->at(i)->label();
                                                   ^
src/PeerConnectionManager.cpp: In member function ‘const Json::Value PeerConnectionManager::getPeerConnectionList()’:
src/PeerConnectionManager.cpp:650:35: error: ‘class webrtc::MediaStreamInterface’ has no member named ‘label’
       stream[localstreams->at(i)->label()] = tracks;
                                   ^
Makefile:94: recipe for target 'src/PeerConnectionManager.o' failed
make: *** [src/PeerConnectionManager.o] Error 1
```

I checked MediaStreamInterface.h file and looks like it has changed. Doesn't have the member named "label" anymore - its renamed to "id".  Once I rename all the "label()" calls to "id()" I am able to build and run ./webrtc_streamer without any issues.

**Comment by mpromonet** [comment] 2018-03-23 20:22
Hi,
This is a duplicate of #106 and it is fix in commit https://github.com/mpromonet/webrtc-streamer/commit/456667de427809701a5eadc4eb34e420ccad4d20
Best Regards,
Michel.

**Closed by mpromonet** 2018-03-23 20:22 UTC
Labels: duplicate
