### ISSUE TITLE
I recommend that,it can use websocket to exchange cadidate signal,or can give command to contact the server,then use can use java webscoket to contact with the server

### ISSUE THREAD

**Issue by JokerSora** [mpromonet/webrtc-streamer#414] opened 2021-04-23 01:35 UTC
muti rtsp streams had a problem that it happended delay as chrome has a limit of six connnections to a same host:port at one time,so here we must change the fetch api in the web model to xmlhttprequest api which can set a timeout of 200 so the maxdelay is less than 500(as the tcp needs time)
that's all ,thanks

**Comment by mpromonet** [comment] 2021-04-23 06:51
Hi @JokerSora 

I never took the time to do this, civetweb support websocket, I guess you should smoothly implement ICE negociation over websocket.
Feel free to submit PR.

Best Regards,
Michel.

**Comment by mpromonet** [comment] 2021-07-17 18:54
duplicate of https://github.com/mpromonet/webrtc-streamer/issues/368

**Closed by mpromonet** 2021-07-17 18:54 UTC
Labels: discussion, duplicate
