### ISSUE TITLE
Init() failed to create the ADM

### ISSUE THREAD

**Issue by abhisit** [mpromonet/webrtc-streamer#85] opened 2017-11-16 08:55 UTC
The package is webrtc-streamer v0.0.7 x86_64, pre-compiled official release.
My machine is Ubuntu 16.04.3 x86_64.

$ ./webrtc-streamer rtsp://USER:PASSWORD@IP.IP.IP.IP:PORT/Streaming/Channels/1/
Logger level:4
[000:000] [1260] (audio_device_impl.cc:248): Failed to create the platform specific ADM implementation.
[000:001] [1260] (audio_device_impl.cc:248): Failed to create the platform specific ADM implementation.
[000:001] [1260] (voe_base_impl.cc:167): Init() failed to create the ADM

\#
\# Fatal error in ../../../media/engine/webrtcvoiceengine.cc, line 286
\# last system error: 0
\# Check failed: 0 == voe_wrapper_->base()->Init(adm_.get(), apm(), decoder_factory_) (0 vs. -1)
\# 
\#

==== C stack trace ===============================

./webrtc-streamer() [0x463662]
./webrtc-streamer() [0x4a02e3]
./webrtc-streamer() [0x49e5fa]
./webrtc-streamer() [0x5e6dce]
./webrtc-streamer() [0x474739]
./webrtc-streamer() [0x474b83]
./webrtc-streamer() [0x5e5047]
./webrtc-streamer() [0x586942]
./webrtc-streamer() [0x5880ae]
./webrtc-streamer() [0x586782]
./webrtc-streamer() [0x43e708]
./webrtc-streamer() [0x43e520]
./webrtc-streamer() [0x43ec17]
./webrtc-streamer() [0x41b6c2]
./webrtc-streamer() [0x417a5e]
16: __libc_start_main
./webrtc-streamer() [0x40d8c9]
Aborted (core dumped)

**Comment by mpromonet** [comment] 2017-11-16 21:14
Hi,
Did you install libasound ?
Best regards
Michel

**Comment by abhisit** [comment] 2017-11-17 01:39
Hi,

Thanks @mpromonet 

I am install libasound.
# apt-get install libasound2-dev

Nothing difference.

Thank you,
Abhisit.

**Comment by mpromonet** [comment] 2017-11-18 13:15
@abhisit
Hi,
It is an exact duplicate of #83 
The workaround is to add -a option.
I will change the default audiolayer
Best Regards,
Michel.

**Closed by mpromonet** 2017-11-18 13:15 UTC
Labels: duplicate
